### ISSUE TITLE
logstation seems to crash if BROWSE is not available 

### ISSUE THREAD

**Issue by Kkevsterrr** [jdrews/logstation#33]
I'm excited to use logstation and I'd like to configure to use it automatically in my environment. However, when I start a logstation instance programatically, it immediately dies: 
```
Exception in thread "main" java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.awt.Desktop.checkActionSupport(Desktop.java:225)
	at java.awt.Desktop.browse(Desktop.java:381)
	at com.jdrews.logstation.LogStation$delayedInit$body.apply(LogStation.scala:124)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.App$class.main(App.scala:71)
	at com.jdrews.logstation.LogStation$.main(LogStation.scala:34)
	at com.jdrews.logstation.LogStation.main(LogStation.scala)
```
Am I missing something with how I should run it?

**Comment by jdrews** [comment]
Hmm that's happening because it's trying to load the browser window. Some quick googling seems to suggest that `java.awt.Desktop.browse` has poor support for Linux desktops. Perhaps you're on Linux or something similar? 

Does it flat out crash or do you just get that error? If so just go to `http://127.0.0.1:8884` and it should be available.

**Comment by Kkevsterrr** [comment]
Yup, I’m on Linux. Ideally I would like to be able to run logstation in the background and be able to access the server from other computers, and not be forced into using Desktop.browse. It seems to just flat out crash. 

To reproduce, I made this python file “test.py":
``` 
$ cat test.py
import os
os.sytem(“java -jar logstation-0.3.10.jar &”)
$ sudo python3 test.py
… # <— crash I sent you before
```
Interestingly, it seems to be able to trigger the Browse when I don’t run with `sudo`. Ideally it would fail gracefully though if it could not Browse so this could be used in a headless context. I hope this helps!

**Comment by jdrews** [comment]
I've isolated where this error is coming from, but I wasn't able to recreate it. I've put in some checks to make it continue on if it can't launch a browser. Please give it a go with the new 0.3.11 pre-release:
https://github.com/jdrews/logstation/releases/tag/0.3.11
https://github.com/jdrews/logstation/releases/download/0.3.11/logstation-0.3.11.jar

**Comment by jdrews** [comment]
Tested on #34 here: https://github.com/jdrews/logstation/issues/34#issuecomment-429510556

Closing.
